export const Works = [
  {
    id: 1,
    title: "Portfolio Site",
    src: "PortfolioImg.avif",
    site: "",
    link: "https://github.com/Yunsuyeong/myPortfolio",
    description:
      "A personal site that collects what I studied and made personally.",
  },
  {
    id: 2,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 3,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 4,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 5,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 6,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
];
