export const Works = [
  {
    id: 1,
    title: "Portfolio Site",
    src: "PortfolioImg.avif",
    site: "",
    link: "https://github.com/Yunsuyeong/myPortfolio",
    description:
      "현재까지 공부했던 내용과 개인 프로젝트로 진행한 내용을 모아서 정리해 놓은 개인용 사이트입니다. (현재 보고 있는 사이트입니다)",
  },
  {
    id: 2,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 3,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 4,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 5,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
  {
    id: 6,
    title: "XXXXXXXXXX",
    src: "",
    site: "",
    link: "",
    description: "xxxxxxxxxx",
  },
];
